
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import testcrud.KoneksiDB;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Qoriatul Masfufah
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        setTanggal();
        setJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        labeljam = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNIS = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbData = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tfTempat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rdLaki = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAlamat = new javax.swing.JTextArea();
        tfKelas = new javax.swing.JTextField();
        rdPrm = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        Tanggal = new com.toedter.calendar.JDateChooser();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btRefresh = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btSave = new javax.swing.JButton();
        btPrint = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 51, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM BIODATA SISWA SMK TELKOM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 10, 390, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("The Real Informatic School");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 50, 210, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tanggal");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(680, 20, 60, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Jam");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(680, 50, 70, 20);

        tanggal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tanggal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tanggal);
        tanggal.setBounds(760, 20, 70, 20);

        labeljam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labeljam.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(labeljam);
        labeljam.setBounds(760, 50, 90, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 920, 100);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("NIS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 140, 30, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 190, 60, 20);

        tfNIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNISActionPerformed(evt);
            }
        });
        getContentPane().add(tfNIS);
        tfNIS.setBounds(40, 160, 190, 30);
        getContentPane().add(tfNama);
        tfNama.setBounds(40, 210, 190, 30);

        tbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama Siswa", "Jenis Kelamin", "Kelas", "Email", "Alamat", "Tempat Lahir", "Tanggal Lahir"
            }
        ));
        tbData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbData);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(300, 170, 610, 400);

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Tanggal lahir");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(40, 180, 80, 20);

        tfTempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTempatActionPerformed(evt);
            }
        });
        jPanel2.add(tfTempat);
        tfTempat.setBounds(40, 150, 190, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Email");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(40, 330, 30, 14);

        buttonGroup1.add(rdLaki);
        rdLaki.setText("Laki-laki");
        jPanel2.add(rdLaki);
        rdLaki.setBounds(40, 260, 70, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Kelas");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 280, 50, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Jenis Kelamin");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 230, 80, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Alamat");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(40, 380, 60, 14);
        jPanel2.add(tfEmail);
        tfEmail.setBounds(40, 350, 190, 30);

        taAlamat.setColumns(20);
        taAlamat.setRows(5);
        jScrollPane1.setViewportView(taAlamat);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(40, 400, 190, 60);
        jPanel2.add(tfKelas);
        tfKelas.setBounds(40, 300, 190, 30);

        buttonGroup1.add(rdPrm);
        rdPrm.setText("Perempuan");
        jPanel2.add(rdPrm);
        rdPrm.setBounds(110, 260, 90, 23);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Tempat Lahir");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(40, 130, 80, 20);
        jPanel2.add(Tanggal);
        Tanggal.setBounds(40, 200, 190, 30);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(40, 30, 220, 80);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("ISIAN DATA SISWA");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 0, 120, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 110, 280, 470);

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);
        getContentPane().add(jPanel3);
        jPanel3.setBounds(290, 160, 630, 420);

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));
        jPanel4.setLayout(null);

        btRefresh.setBackground(new java.awt.Color(255, 153, 51));
        btRefresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btRefresh.setText("Refresh");
        btRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshActionPerformed(evt);
            }
        });
        jPanel4.add(btRefresh);
        btRefresh.setBounds(320, 10, 80, 23);

        btDelete.setBackground(new java.awt.Color(255, 153, 51));
        btDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btDelete.setForeground(new java.awt.Color(255, 255, 255));
        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(btDelete);
        btDelete.setBounds(140, 10, 80, 23);

        btClear.setBackground(new java.awt.Color(255, 153, 51));
        btClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btClear.setForeground(new java.awt.Color(255, 255, 255));
        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        jPanel4.add(btClear);
        btClear.setBounds(230, 10, 80, 23);

        btEdit.setBackground(new java.awt.Color(255, 153, 51));
        btEdit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btEdit.setForeground(new java.awt.Color(255, 255, 255));
        btEdit.setText("Edit");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });
        jPanel4.add(btEdit);
        btEdit.setBounds(410, 10, 80, 23);

        btSave.setBackground(new java.awt.Color(255, 153, 51));
        btSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSave.setForeground(new java.awt.Color(255, 255, 255));
        btSave.setText("Save");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        jPanel4.add(btSave);
        btSave.setBounds(50, 10, 80, 23);

        btPrint.setBackground(new java.awt.Color(255, 153, 51));
        btPrint.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btPrint.setForeground(new java.awt.Color(255, 255, 255));
        btPrint.setText("Print");
        btPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintActionPerformed(evt);
            }
        });
        jPanel4.add(btPrint);
        btPrint.setBounds(500, 10, 70, 23);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(290, 110, 630, 40);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(10, 110, 100, 100);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Jenis Kelamin");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 300, 80, 20);

        setBounds(0, 0, 933, 634);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNISActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        // TODO add your handling code here:
       SimpleDateFormat dateFormat= new SimpleDateFormat("yyy-MM-dd");
       String tanggal = dateFormat.format(Tanggal.getDate());
       
        if ("".equals(tfNIS.getText())||"".equals(tfNama.getText())||"".equals(taAlamat.getText())||"".equals(tfKelas.getText())||"".equals(tfEmail.getText())||"".equals(tfTempat.getText())||"".equals(tanggal)) {
           JOptionPane.showMessageDialog(rdPrm, evt);
        }else{
            String JK = "";
            if (rdLaki.isSelected()) {
                JK = "L";
            }else{
                JK ="P";
            }
            String SQL = "INSERT INTO t_siswa(NIS,NamaSiswa,JenisKelamin,Kelas, Email,Alamat,Tempat_Lahir,Tanggal_Lahir)" + 
                    "VALUES('"+tfNIS.getText()+"','"+tfNama.getText()+"','"+JK+"','"+tfKelas.getText()+"','"+tfEmail.getText()+"','"+taAlamat.getText()+"','"+tfTempat.getText()+"','"+tanggal+"')";
            int status = KoneksiDB.execute(SQL);
            if(status == 1){
                JOptionPane.showMessageDialog(this,"Data berhasil ditambahkan","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectedData();
            }
            else{
                JOptionPane.showMessageDialog(this,"Data gagal ditambahkan","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        }
       
       
    }//GEN-LAST:event_btSaveActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
        
        int baris = tbData.getSelectedRow();
        if (baris != -1){
            String NIS = tbData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if(status ==1){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Pilih Baris Data Terlebih Dahulu", "EROR", JOptionPane.WARNING_MESSAGE);
        }   
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // TODO add your handling code here:
        tfNama.setText("");
        tfNIS.setText("");
        tfKelas.setText("");
        buttonGroup1.clearSelection();
        taAlamat.setText("");
        tfEmail.setText("");
        Tanggal.setCalendar(null);
        tfTempat.setText("");
    }//GEN-LAST:event_btClearActionPerformed

    private void btRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshActionPerformed
            selectedData();
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_btRefreshActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        // TODO add your handling code here:
        
        
        if("".equals(tfNIS.getText()) || "".equals(taAlamat.getText()) ||
                "".equals(tfKelas.getText()) || "".equals(tfNama.getText()) ||
                "".equals(tfEmail.getText()) || "".equals(tfTempat.getText())) 
        {
            JOptionPane.showMessageDialog(this, "Harap Lengakapi Data", "ERROR", JOptionPane.WARNING_MESSAGE);
        } else{
            int baris = tbData.getSelectedRow();
            String nis = tbData.getValueAt(baris, 0).toString();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyy-MM-dd");
            String JK = "";
                if (rdLaki.isSelected()){
                    JK = "L";
                }else {
                    JK = "P";
                }
            String SQL = "UPDATE t_siswa SET `NIS`='"+tfNIS.getText()
                    +"',`NamaSiswa`='"+tfNama.getText()
                    +"',`JenisKelamin`='"+JK
                    +"',`Kelas`='"+tfKelas.getText()
                    +"',`Email`='"+tfEmail.getText()
                    +"',`Alamat`='"+taAlamat.getText()
                    +"',`Tempat_Lahir`='"+tfTempat.getText()
                    +"',`Tanggal_Lahir`='"+Tanggal.getDate()
                    +"' WHERE NIS='"+nis+"'";
                    
            int status = KoneksiDB.execute(SQL);
            if (status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectedData();
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Error", JOptionPane.WARNING_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btEditActionPerformed

    private void tbDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDataMouseClicked
        // TODO add your handling code here:
        
        int baris = tbData.getSelectedRow();
        if (baris != -1){
            tfNIS.setText(tbData.getValueAt(baris, 0).toString());
            tfNama.setText(tbData.getValueAt(baris, 1).toString());
            if("Laki-laki".equals(tbData.getValueAt(baris, 2).toString())){
                rdLaki.setSelected(true);
            } else{
                rdPrm.setSelected(true);
            }
            
            tfKelas.setText(tbData.getValueAt(baris, 3).toString());
            tfEmail.setText(tbData.getValueAt(baris, 4).toString());
            taAlamat.setText(tbData.getValueAt(baris, 5).toString());
            tfTempat.setText(tbData.getValueAt(baris, 6).toString());
            
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat = null;
            try 
            {
                dateFormat = date.parse(tbData.getValueAt(baris, 7).toString());
            } catch (ParseException ex) 
            {
               
            }

            Tanggal.setDate(dateFormat);
        }
    }//GEN-LAST:event_tbDataMouseClicked

    private void tfTempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTempatActionPerformed

    private void btPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintActionPerformed
        // TODO add your handling code here:
        
        MessageFormat header = new MessageFormat("Biodata Siswa SMK Telkom Malang");
        MessageFormat footer = new MessageFormat("Page (0,number,integer) ");
        try{
            tbData.print(JTable.PrintMode.FIT_WIDTH,header,footer,true,null,true,null);
        } catch (java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }
    
    public void setTanggal(){
    java.util.Date skrng = new java.util.Date();
    java.text.SimpleDateFormat kal = new
    java.text.SimpleDateFormat("dd/MM/YYYY");
    tanggal.setText(kal.format(skrng));
    }
    
    public void setJam(){
        ActionListener taskPerformer = new ActionListener(){
            String nol_jam,nol_detik,nol_menit;
            public void actionPerformed(ActionEvent evt){
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if(nilai_jam <= 9){
                    nol_jam = "0";
                }
                if(nilai_detik <= 9){
                    nol_detik = "0";
                }
            String jam  = Integer.toString(nilai_jam);
            String menit =  Integer.toString(nilai_menit);
            String detik = Integer.toString(nilai_detik);
            labeljam.setText("Jam "+jam + ":" + menit + ":" + detik);
            }
        };
    new Timer (100, taskPerformer).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Tanggal;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btPrint;
    private javax.swing.JButton btRefresh;
    private javax.swing.JButton btSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labeljam;
    private javax.swing.JRadioButton rdLaki;
    private javax.swing.JRadioButton rdPrm;
    private javax.swing.JTextArea taAlamat;
    private javax.swing.JLabel tanggal;
    private javax.swing.JTable tbData;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfKelas;
    private javax.swing.JTextField tfNIS;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfTempat;
    // End of variables declaration//GEN-END:variables


    private void selectedData() {
    String kolom[] = {"NIS","NamaSiswa","JenisKelamin","Kelas","Email","Alamat","TempatLahir","TanggalLahir"};
                DefaultTableModel dtm = new DefaultTableModel(null, kolom);
                String SQL = "SELECT * FROM t_siswa";
                ResultSet rs = KoneksiDB.executeQuery(SQL);
                try{
                    while(rs.next()){
                        String NIS = rs.getString(1);
                        String NamaSiswa = rs.getString(2);
                        String JenisKelamin = "";
                        if("L".equals(rs.getString(3))){
                            JenisKelamin = "Laki-laki";
                        } else{
                            JenisKelamin = "Perempuan";
                        }
                        String Kelas = rs.getString(4);
                        String Email = rs.getString(5);
                        String Alamat = rs.getString(6);
                        String TempatLahir = rs.getString(7);
                        String TanggalLahir = rs.getString(8);
                        String data[] = {NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat,TempatLahir, TanggalLahir};
                        dtm.addRow(data);
                    }
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
              tbData.setModel(dtm);    }

}
